name: NumPy

# Controls when the action will run.
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/numpy.yml'

  schedule:
  #        ┌───────────── minute (0 - 59)
  #        │ ┌───────────── hour (0 - 23)
  #        │ │ ┌───────────── day of the month (1 - 31)
  #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #        │ │ │ │ │
  - cron: "0 2 * * 0"

jobs:
  numpy:
    name: NumPy ${{ matrix.os }}/${{ matrix.python_version }}
    env:
      BITS: 64
      NPY_USE_BLAS_ILP64: '1'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python_version: [pypy-3.10-nightly]

    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        repository: numpy/numpy
        path: repo
        submodules: recursive
        fetch-depth: 0

    - name: Install pkg-config
      run: |
        choco install -y --checksum 6004DF17818F5A6DBF19CB335CC92702 pkgconfiglite
      if: matrix.os == 'windows-latest'

    - uses: actions/setup-python@v5.0.0
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install gfortran (macOS)
      run: |
        source repo/tools/wheels/gfortran_utils.sh
        install_gfortran
      if: matrix.os == 'macos-latest'

    - name: Install dependencies and scipy-openblas
      run: |
        cd repo
        python -m pip install --upgrade pip
        python -m pip install ninja
        python -m pip install -r requirements/test_requirements.txt spin scipy-openblas32
        spin config-openblas --with-scipy-openblas=32

    - name: Install NumPy
      env:
        PKG_CONFIG_PATH: ${{ github.workspace }}/repo/.openblas
      run: |
        cd repo
        python -c "import os; print('PKG_CONFIG_PATH', os.environ['PKG_CONFIG_PATH'])"
        python -m pip install . -v -Csetup-args="--vsenv"

    - name: Test
      shell: bash
      run: |
        # do not cd into the repo directory so we can import numpy
        cp repo/pytest.ini . 
        export LIBRARY_PATH="$LIBRARY_PATH:/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib"
        pytest --pyargs numpy -rsx
