name: NumPy

# Controls when the action will run.
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/numpy.yml'

  schedule:
  #        ┌───────────── minute (0 - 59)
  #        │ ┌───────────── hour (0 - 23)
  #        │ │ ┌───────────── day of the month (1 - 31)
  #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #        │ │ │ │ │
  - cron: "0 2 * * 0"

jobs:
  numpy:
    name: NumPy ${{ matrix.os }}/${{ matrix.python_version }}
    env:
      BITS: 64
      NPY_USE_BLAS_ILP64: '1'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python_version: [pypy-3.11-nightly]

    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        repository: numpy/numpy
        path: repo
        submodules: recursive
        fetch-depth: 0

    - uses: actions/setup-python@v5.3.0
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install dependencies
      run: |
        cd repo
        python -m pip install --upgrade pip
        python -m pip install ninja
        python -m pip install -r requirements/test_requirements.txt spin
        python -m pip install -r requirements/build_requirements.txt
        pip install -r requirements/ci_requirements.txt
        # Use a newer cython
        python -m pip install git+https://github.com/cython/cython.git

    - name: Install pkg-config
      run: |
        choco install -y --checksum 6004DF17818F5A6DBF19CB335CC92702 pkgconfiglite
      if: ${{ startswith(matrix.os, 'windows') }}

    - name: Install NumPy (use Accelerate)
      if: matrix.os == 'macos-latest'
      run: |
        cd repo
        spin build -- -Ddisable-optimization=true -Dallow-noblas=false

    - name: Install NumPy (use scipy-openblas)
      if: matrix.os != 'macos-latest'
      shell: bash
      run: |
        cd repo
        export PKG_CONFIG_PATH=$PWD/.openblas
        spin build -j2 --with-scipy-openblas=32 -j2 -- --vsenv

    - name: Test
      run: |
        cd repo
        spin test -- --timeout=600 --durations=10
